# name          lanes                                alias                     index      speed
Ethernet1       9,10,11,12                           fourhundredGigE0/1        0          400000     
Ethernet2       5,6,7,8                              fourhundredGigE0/2        1          400000     
Ethernet3       1,2,3,4                              fourhundredGigE0/3        2          400000     
Ethernet4       13,14,15,16                          fourhundredGigE0/4        3          400000     
Ethernet5       29,30,31,32                          fourhundredGigE0/5        4          400000     
Ethernet6       21,22,23,24                          fourhundredGigE0/6        5          400000     
Ethernet7       17,18,19,20                          fourhundredGigE0/7        6          400000     
Ethernet8       25,26,27,28                          fourhundredGigE0/8        7          400000     
Ethernet9       45,46,47,48                          fourhundredGigE0/9        8          400000     
Ethernet10      37,38,39,40                          fourhundredGigE0/10       9          400000     
Ethernet11      33,34,35,36                          fourhundredGigE0/11       10         400000     
Ethernet12      41,42,43,44                          fourhundredGigE0/12       11         400000     
Ethernet13      61,62,63,64                          fourhundredGigE0/13       12         400000     
Ethernet14      53,54,55,56                          fourhundredGigE0/14       13         400000     
Ethernet15      49,50,51,52                          fourhundredGigE0/15       14         400000     
Ethernet16      57,58,59,60                          fourhundredGigE0/16       15         400000     
Ethernet17      77,78,79,80                          fourhundredGigE0/17       16         400000     
Ethernet18      69,70,71,72                          fourhundredGigE0/18       17         400000     
Ethernet19      65,66,67,68                          fourhundredGigE0/19       18         400000     
Ethernet20      73,74,75,76                          fourhundredGigE0/20       19         400000     
Ethernet21      93,94,95,96                          fourhundredGigE0/21       20         400000     
Ethernet22      85,86,87,88                          fourhundredGigE0/22       21         400000     
Ethernet23      81,82,83,84                          fourhundredGigE0/23       22         400000     
Ethernet24      89,90,91,92                          fourhundredGigE0/24       23         400000     
Ethernet25      109,110,111,112                      fourhundredGigE0/25       24         400000     
Ethernet26      101,102,103,104                      fourhundredGigE0/26       25         400000     
Ethernet27      97,98,99,100                         fourhundredGigE0/27       26         400000     
Ethernet28      105,106,107,108                      fourhundredGigE0/28       27         400000     
Ethernet29      121,122,123,124                      fourhundredGigE0/29       28         400000     
Ethernet30      117,118,119,120                      fourhundredGigE0/30       29         400000     
Ethernet31      113,114,115,116                      fourhundredGigE0/31       30         400000     
Ethernet32      125,126,127,128                      fourhundredGigE0/32       31         400000     
Ethernet33      141,142,143,144                      fourhundredGigE0/33       32         400000     
Ethernet34      129,130,131,132                      fourhundredGigE0/34       33         400000     
Ethernet35      133,134,135,136                      fourhundredGigE0/35       34         400000     
Ethernet36      137,138,139,140                      fourhundredGigE0/36       35         400000     
Ethernet37      153,154,155,156                      fourhundredGigE0/37       36         400000     
Ethernet38      145,146,147,148                      fourhundredGigE0/38       37         400000     
Ethernet39      149,150,151,152                      fourhundredGigE0/39       38         400000     
Ethernet40      157,158,159,160                      fourhundredGigE0/40       39         400000     
Ethernet41      169,170,171,172                      fourhundredGigE0/41       40         400000     
Ethernet42      161,162,163,164                      fourhundredGigE0/42       41         400000     
Ethernet43      165,166,167,168                      fourhundredGigE0/43       42         400000     
Ethernet44      173,174,175,176                      fourhundredGigE0/44       43         400000     
Ethernet45      185,186,187,188                      fourhundredGigE0/45       44         400000     
Ethernet46      177,178,179,180                      fourhundredGigE0/46       45         400000     
Ethernet47      181,182,183,184                      fourhundredGigE0/47       46         400000     
Ethernet48      189,190,191,192                      fourhundredGigE0/48       47         400000     
Ethernet49      201,202,203,204                      fourhundredGigE0/49       48         400000     
Ethernet50      193,194,195,196                      fourhundredGigE0/50       49         400000     
Ethernet51      197,198,199,200                      fourhundredGigE0/51       50         400000     
Ethernet52      205,206,207,208                      fourhundredGigE0/52       51         400000     
Ethernet53      217,218,219,220                      fourhundredGigE0/53       52         400000     
Ethernet54      209,210,211,212                      fourhundredGigE0/54       53         400000     
Ethernet55      213,214,215,216                      fourhundredGigE0/55       54         400000     
Ethernet56      221,222,223,224                      fourhundredGigE0/56       55         400000     
Ethernet57      233,234,235,236                      fourhundredGigE0/57       56         400000     
Ethernet58      225,226,227,228                      fourhundredGigE0/58       57         400000     
Ethernet59      229,230,231,232                      fourhundredGigE0/59       58         400000     
Ethernet60      237,238,239,240                      fourhundredGigE0/60       59         400000     
Ethernet61      253,254,255,256                      fourhundredGigE0/61       60         400000     
Ethernet62      241,242,243,244                      fourhundredGigE0/62       61         400000     
Ethernet63      245,246,247,248                      fourhundredGigE0/63       62         400000     
Ethernet64      249,250,251,252                      fourhundredGigE0/64       63         400000     
Ethernet65      258                                  tenGigE0/65               64         10000
Ethernet66      257                                  tenGigE0/66               65         10000
