obj-m += wb-i2c-designware-core.o
wb-i2c-designware-core-y := i2c-designware-common.o
wb-i2c-designware-core-y += i2c-designware-master.o
obj-m += wb-i2c-designware-platform.o
wb-i2c-designware-platform-y := i2c-designware-platdrv.o
wb-i2c-designware-platform-y += i2c-designware-baytrail.o
obj-m += wb-i2c-designware-pci.o
wb-i2c-designware-pci-y = i2c-designware-pcidrv.o
