# name                lanes                        alias                           index        speed     admin_status
Ethernet1             32,33,34,35                  eth1                            1            400000     up
Ethernet2             36,37,38,39                  eth2                            2            400000     up
Ethernet3             40,41,42,43                  eth3                            3            400000     up
Ethernet4             44,45,46,47                  eth4                            4            400000     up
Ethernet5             48,49,50,51                  eth5                            5            400000     up
Ethernet6             52,53,54,55                  eth6                            6            400000     up
Ethernet7             56,57,58,59                  eth7                            7            400000     up
Ethernet8             60,61,62,63                  eth8                            8            400000     up
Ethernet9             120,121,122,123              eth9                            9            400000     up
Ethernet10            124,125,126,127              eth10                           10           400000     up
Ethernet11            112,113,114,115              eth11                           11           400000     up
Ethernet12            116,117,118,119              eth12                           12           400000     up
Ethernet13            104,105,106,107              eth13                           13           400000     up
Ethernet14            108,109,110,111              eth14                           14           400000     up
Ethernet15            96,97,98,99                  eth15                           15           400000     up
Ethernet16            100,101,102,103              eth16                           16           400000     up
Ethernet17            64,65,66,67                  eth17                           17           400000     up
Ethernet18            68,69,70,71                  eth18                           18           400000     up
Ethernet19            72,73,74,75                  eth19                           19           400000     up
Ethernet20            76,77,78,79                  eth20                           20           400000     up
Ethernet21            80,81,82,83                  eth21                           21           400000     up
Ethernet22            84,85,86,87                  eth22                           22           400000     up
Ethernet23            88,89,90,91                  eth23                           23           400000     up
Ethernet24            92,93,94,95                  eth24                           24           400000     up
Ethernet25            24,25,26,27                  eth25                           25           400000     up
Ethernet26            28,29,30,31                  eth26                           26           400000     up
Ethernet27            16,17,18,19                  eth27                           27           400000     up
Ethernet28            20,21,22,23                  eth28                           28           400000     up
Ethernet29            8,9,10,11                    eth29                           29           400000     up
Ethernet30            12,13,14,15                  eth30                           30           400000     up
Ethernet31            0,1,2,3                      eth31                           31           400000     up
Ethernet32            4,5,6,7                      eth32                           32           400000     up
Ethernet33            160,161,162,163              eth33                           33           400000     up
Ethernet34            164,165,166,167              eth34                           34           400000     up
Ethernet35            168,169,170,171              eth35                           35           400000     up
Ethernet36            172,173,174,175              eth36                           36           400000     up
Ethernet37            176,177,178,179              eth37                           37           400000     up
Ethernet38            180,181,182,183              eth38                           38           400000     up
Ethernet39            184,185,186,187              eth39                           39           400000     up
Ethernet40            188,189,190,191              eth40                           40           400000     up
Ethernet41            248,249,250,251              eth41                           41           400000     up
Ethernet42            252,253,254,255              eth42                           42           400000     up
Ethernet43            240,241,242,243              eth43                           43           400000     up
Ethernet44            244,245,246,247              eth44                           44           400000     up
Ethernet45            232,233,234,235              eth45                           45           400000     up
Ethernet46            236,237,238,239              eth46                           46           400000     up
Ethernet47            224,225,226,227              eth47                           47           400000     up
Ethernet48            228,229,230,231              eth48                           48           400000     up
Ethernet49            192,193,194,195              eth49                           49           400000     up
Ethernet50            196,197,198,199              eth50                           50           400000     up
Ethernet51            200,201,202,203              eth51                           51           400000     up
Ethernet52            204,205,206,207              eth52                           52           400000     up
Ethernet53            208,209,210,211              eth53                           53           400000     up
Ethernet54            212,213,214,215              eth54                           54           400000     up
Ethernet55            216,217,218,219              eth55                           55           400000     up
Ethernet56            220,221,222,223              eth56                           56           400000     up
Ethernet57            152,153,154,155              eth57                           57           400000     up
Ethernet58            156,157,158,159              eth58                           58           400000     up
Ethernet59            144,145,146,147              eth59                           59           400000     up
Ethernet60            148,149,150,151              eth60                           60           400000     up
Ethernet61            136,137,138,139              eth61                           61           400000     up
Ethernet62            140,141,142,143              eth62                           62           400000     up
Ethernet63            128,129,130,131              eth63                           63           400000     up
Ethernet64            132,133,134,135              eth64                           64           400000     up
