# name          lanes                                alias                              speed      fec    index
Ethernet1       1,2,3,4                              fourhundredGigE0/1                 400000     rs     0
Ethernet2       5,6,7,8                              fourhundredGigE0/2                 400000     rs     1
Ethernet3       9,10,11,12                           fourhundredGigE0/3                 400000     rs     2
Ethernet4       13,14,15,16                          fourhundredGigE0/4                 400000     rs     3
Ethernet5       25,26,27,28                          fourhundredGigE0/5                 400000     rs     4
Ethernet6       29,30,31,32                          fourhundredGigE0/6                 400000     rs     5
Ethernet7       33,34,35,36                          fourhundredGigE0/7                 400000     rs     6
Ethernet8       37,38,39,40                          fourhundredGigE0/8                 400000     rs     7
Ethernet9       17,18,19,20                          fourhundredGigE0/9                 400000     rs     8
Ethernet10      21,22,23,24                          fourhundredGigE0/10                400000     rs     9
Ethernet11      41,42,43,44                          fourhundredGigE0/11                400000     rs     10
Ethernet12      45,46,47,48                          fourhundredGigE0/12                400000     rs     11
Ethernet13      49,50,51,52                          fourhundredGigE0/13                400000     rs     12
Ethernet14      53,54,55,56                          fourhundredGigE0/14                400000     rs     13
Ethernet15      57,58,59,60                          fourhundredGigE0/15                400000     rs     14
Ethernet16      61,62,63,64                          fourhundredGigE0/16                400000     rs     15
Ethernet17      65,66,67,68                          fourhundredGigE0/17                400000     rs     16
Ethernet18      69,70,71,72                          fourhundredGigE0/18                400000     rs     17
Ethernet19      73,74,75,76                          fourhundredGigE0/19                400000     rs     18
Ethernet20      77,78,79,80                          fourhundredGigE0/20                400000     rs     19
Ethernet21      81,82,83,84                          fourhundredGigE0/21                400000     rs     20
Ethernet22      85,86,87,88                          fourhundredGigE0/22                400000     rs     21
Ethernet23      89,90,91,92                          fourhundredGigE0/23                400000     rs     22
Ethernet24      93,94,95,96                          fourhundredGigE0/24                400000     rs     23
Ethernet25      97,98,99,100                         fourhundredGigE0/25                400000     rs     24
Ethernet26      101,102,103,104                      fourhundredGigE0/26                400000     rs     25
Ethernet27      105,106,107,108                      fourhundredGigE0/27                400000     rs     26
Ethernet28      109,110,111,112                      fourhundredGigE0/28                400000     rs     27
Ethernet29      113,114,115,116                      fourhundredGigE0/29                400000     rs     28
Ethernet30      117,118,119,120                      fourhundredGigE0/30                400000     rs     29
Ethernet31      137,138,139,140                      fourhundredGigE0/31                400000     rs     30
Ethernet32      141,142,143,144                      fourhundredGigE0/32                400000     rs     31
Ethernet33      121,122,123,124                      fourhundredGigE0/33                400000     rs     32
Ethernet34      125,126,127,128                      fourhundredGigE0/34                400000     rs     33
Ethernet35      129,130,131,132                      fourhundredGigE0/35                400000     rs     34
Ethernet36      133,134,135,136                      fourhundredGigE0/36                400000     rs     35
Ethernet37      145,146,147,148                      fourhundredGigE0/37                400000     rs     36
Ethernet38      149,150,151,152                      fourhundredGigE0/38                400000     rs     37
Ethernet39      153,154,155,156                      fourhundredGigE0/39                400000     rs     38
Ethernet40      157,158,159,160                      fourhundredGigE0/40                400000     rs     39
