#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
import sys
import time
sys.path.append('/usr/local/bin')
from platform_util import *

PLATFORM_REBOOT_DEBUG_FILE = "/etc/.platform_reboot_debug"

debuglevel = 0

def record_syslog_debug(s):
    if debuglevel:
        syslog.openlog("PLATFORM_REBOOT_DEBUG", syslog.LOG_PID)
        syslog.syslog(syslog.LOG_DEBUG, s)

def debug_init():
    global debuglevel
    global PLATFORM_REBOOT_DEBUG_FILE
    if os.path.exists(PLATFORM_REBOOT_DEBUG_FILE):
        debuglevel = 1
    else:
        debuglevel = 0

RESET_MAC_CMD = [
    {"cmd": "setpci -s 00:1c.0 0x50.W=0x0050", "gettype": "cmd"},
    {"path": "/dev/cpld8", "offset": 0xe0, "read_len": 1, "rst_val":0x0, "mask": 0x2, "gettype": "devfile", "value":None},
    {"path": "/dev/cpld8", "offset": 0xe0, "read_len": 1, "rst_val":0x2, "rst_delay":0.1, "mask": 0x2, "gettype": "devfile", "value":None},
]

def reset_mac():
    for cmd in RESET_MAC_CMD:
        mask = cmd.get("mask", None)
        rst_val = cmd.get("rst_val", 0)
        gettype = cmd.get("gettype", None)
        rst_delay = cmd.get("rst_delay", None)
        if gettype not in ["cmd"]:
            ret, value = get_value(cmd)
            if not ret:
                record_syslog_debug("get_value fail, get_type: %s, reson: %s\n" % (cmd['gettype'], value))
                return ret
            record_syslog_debug("get_value success, value: %d\n" % value)
            if mask is not None:
                value &= ~mask
            value |= rst_val
            cmd["value"] = value
        if rst_delay is not None:
            time.sleep(rst_delay)
        ret, log = set_value(cmd)
        if not ret:
            record_syslog_debug("set_value fail, get_type: %s, reson: %s\n" % (cmd['gettype'], value))
            return ret
        record_syslog_debug("set_value success\n")
    return ret

if __name__ == '__main__':
    debug_init()
    print("reset mac")
    ret = reset_mac()
    if not ret:
        print("reset mac fail")
    else:
        print("reset mac success")