# name            lanes                            alias           index      speed       admin_status
Ethernet1         32,33,34,35                      eth-0-1         1          100000        up
Ethernet2         36,37,38,39                      eth-0-2         2          100000        up
Ethernet3         0,4,8,12                         eth-0-3         3          100000        up
Ethernet4         16,20,24,28                      eth-0-4         4          100000        up
Ethernet5         40,44,48,52                      eth-0-5         5          100000        up
Ethernet6         56,60,64,68                      eth-0-6         6          100000        up
Ethernet7         72,73,74,75                      eth-0-7         7          100000        up
Ethernet8         76,77,78,79                      eth-0-8         8          100000        up
Ethernet9         120,121                          eth-0-9         9          100000        up
Ethernet10        122,123                          eth-0-10        10         100000        up
Ethernet11        124,125                          eth-0-11        11         100000        up
Ethernet12        126,127                          eth-0-12        12         100000        up
Ethernet13        80,81                            eth-0-13        13         100000        up
Ethernet14        82,83                            eth-0-14        14         100000        up
Ethernet15        84,85                            eth-0-15        15         100000        up
Ethernet16        86,87                            eth-0-16        16         100000        up
Ethernet17        240,241                          eth-0-17        17         100000        up
Ethernet18        242,243                          eth-0-18        18         100000        up
Ethernet19        244,245                          eth-0-19        19         100000        up
Ethernet20        246,247                          eth-0-20        20         100000        up
Ethernet21        280,281                          eth-0-21        21         100000        up
Ethernet22        282,283                          eth-0-22        22         100000        up
Ethernet23        284,285                          eth-0-23        23         100000        up
Ethernet24        286,287                          eth-0-24        24         100000        up
Ethernet25        232,233,234,235                  eth-0-25        25         100000        up
Ethernet26        236,237,238,239                  eth-0-26        26         100000        up
Ethernet27        200,204,208,212                  eth-0-27        27         100000        up
Ethernet28        216,220,224,228                  eth-0-28        28         100000        up
Ethernet29        160,164,168,172                  eth-0-29        29         100000        up
Ethernet30        176,180,184,188                  eth-0-30        30         100000        up
Ethernet31        192,193,194,195                  eth-0-31        31         100000        up
Ethernet32        196,197,198,199                  eth-0-32        32         100000        up
