# name            lanes                                    alias                 index          speed   
Ethernet1         1,2,3,4                                  twohundredGigE0/1      1            200000
Ethernet2         5,6,7,8                                  twohundredGigE0/2      2            200000
Ethernet3         9,10,11,12                               twohundredGigE0/3      3            200000
Ethernet4         13,14,15,16                              twohundredGigE0/4      4            200000
Ethernet5         17,18,19,20                              twohundredGigE0/5      5            200000
Ethernet6         21,22,23,24                              twohundredGigE0/6      6            200000
Ethernet7         25,26,27,28                              twohundredGigE0/7      7            200000
Ethernet8         29,30,31,32                              twohundredGigE0/8      8            200000
Ethernet9         33,34,35,36                              twohundredGigE0/9      9            200000
Ethernet10        37,38,39,40                              twohundredGigE0/10     10           200000
Ethernet11        41,42,43,44                              twohundredGigE0/11     11           200000
Ethernet12        45,46,47,48                              twohundredGigE0/12     12           200000
Ethernet13        49,50,51,52                              twohundredGigE0/13     13           200000
Ethernet14        53,54,55,56                              twohundredGigE0/14     14           200000
Ethernet15        57,58,59,60                              twohundredGigE0/15     15           200000
Ethernet16        61,62,63,64                              twohundredGigE0/16     16           200000
Ethernet17        65,66,67,68                              twohundredGigE0/17     17           200000
Ethernet18        69,70,71,72                              twohundredGigE0/18     18           200000
Ethernet19        73,74,75,76                              twohundredGigE0/19     19           200000
Ethernet20        77,78,79,80                              twohundredGigE0/20     20           200000
Ethernet21        81,82,83,84                              twohundredGigE0/21     21           200000
Ethernet22        85,86,87,88                              twohundredGigE0/22     22           200000
Ethernet23        89,90,91,92                              twohundredGigE0/23     23           200000
Ethernet24        93,94,95,96                              twohundredGigE0/24     24           200000
Ethernet25        97,98,99,100                             twohundredGigE0/25     25           200000
Ethernet26        101,102,103,104                          twohundredGigE0/26     26           200000
Ethernet27        105,106,107,108                          twohundredGigE0/27     27           200000
Ethernet28        109,110,111,112                          twohundredGigE0/28     28           200000
Ethernet29        113,114,115,116                          twohundredGigE0/29     29           200000
Ethernet30        117,118,119,120                          twohundredGigE0/30     30           200000
Ethernet31        121,122,123,124                          twohundredGigE0/31     31           200000
Ethernet32        125,126,127,128                          twohundredGigE0/32     32           200000
Ethernet33        129,130,131,132                          twohundredGigE0/33     33           200000
Ethernet34        133,134,135,136                          twohundredGigE0/34     34           200000
Ethernet35        137,138,139,140                          twohundredGigE0/35     35           200000
Ethernet36        141,142,143,144                          twohundredGigE0/36     36           200000
Ethernet37        145,146,147,148                          twohundredGigE0/37     37           200000
Ethernet38        149,150,151,152                          twohundredGigE0/38     38           200000
Ethernet39        153,154,155,156                          twohundredGigE0/39     39           200000
Ethernet40        157,158,159,160                          twohundredGigE0/40     40           200000
Ethernet41        161,162,163,164                          twohundredGigE0/41     41           200000
Ethernet42        165,166,167,168                          twohundredGigE0/42     42           200000
Ethernet43        169,170,171,172                          twohundredGigE0/43     43           200000
Ethernet44        173,174,175,176                          twohundredGigE0/44     44           200000
Ethernet45        177,178,179,180                          twohundredGigE0/45     45           200000
Ethernet46        181,182,183,184                          twohundredGigE0/46     46           200000
Ethernet47        185,186,187,188                          twohundredGigE0/47     47           200000
Ethernet48        189,190,191,192                          twohundredGigE0/48     48           200000
Ethernet49        193,194,195,196                          twohundredGigE0/49     49           200000
Ethernet50        197,198,199,200                          twohundredGigE0/50     50           200000
Ethernet51        201,202,203,204                          twohundredGigE0/51     51           200000
Ethernet52        205,206,207,208                          twohundredGigE0/52     52           200000
Ethernet53        209,210,211,212                          twohundredGigE0/53     53           200000
Ethernet54        213,214,215,216                          twohundredGigE0/54     54           200000
Ethernet55        217,218,219,220                          twohundredGigE0/55     55           200000
Ethernet56        221,222,223,224                          twohundredGigE0/56     56           200000
Ethernet57        225,226,227,228                          twohundredGigE0/57     57           200000
Ethernet58        229,230,231,232                          twohundredGigE0/58     58           200000
Ethernet59        233,234,235,236                          twohundredGigE0/59     59           200000
Ethernet60        237,238,239,240                          twohundredGigE0/60     60           200000
Ethernet61        241,242,243,244                          twohundredGigE0/61     61           200000
Ethernet62        245,246,247,248                          twohundredGigE0/62     62           200000
Ethernet63        249,250,251,252                          twohundredGigE0/63     63           200000
Ethernet64        253,254,255,256                          twohundredGigE0/64     64           200000
Ethernet65        257,258,259,260                          twohundredGigE0/65     65           200000
Ethernet66        261,262,263,264                          twohundredGigE0/66     66           200000
Ethernet67        265,266,267,268                          twohundredGigE0/67     67           200000
Ethernet68        269,270,271,272                          twohundredGigE0/68     68           200000
Ethernet69        273,274,275,276                          twohundredGigE0/69     69           200000
Ethernet70        277,278,279,280                          twohundredGigE0/70     70           200000
Ethernet71        281,282,283,284                          twohundredGigE0/71     71           200000
Ethernet72        285,286,287,288                          twohundredGigE0/72     72           200000
Ethernet73        289,290,291,292                          twohundredGigE0/73     73           200000
Ethernet74        293,294,295,296                          twohundredGigE0/74     74           200000
Ethernet75        297,298,299,300                          twohundredGigE0/75     75           200000
Ethernet76        301,302,303,304                          twohundredGigE0/76     76           200000
Ethernet77        305,306,307,308                          twohundredGigE0/77     77           200000
Ethernet78        309,310,311,312                          twohundredGigE0/78     78           200000
Ethernet79        313,314,315,316                          twohundredGigE0/79     79           200000
Ethernet80        317,318,319,320                          twohundredGigE0/80     80           200000
Ethernet81        321,322,323,324                          twohundredGigE0/81     81           200000
Ethernet82        325,326,327,328                          twohundredGigE0/82     82           200000
Ethernet83        329,330,331,332                          twohundredGigE0/83     83           200000
Ethernet84        333,334,335,336                          twohundredGigE0/84     84           200000
Ethernet85        337,338,339,340                          twohundredGigE0/85     85           200000
Ethernet86        341,342,343,344                          twohundredGigE0/86     86           200000
Ethernet87        345,346,347,348                          twohundredGigE0/87     87           200000
Ethernet88        349,350,351,352                          twohundredGigE0/88     88           200000
Ethernet89        353,354,355,356                          twohundredGigE0/89     89           200000
Ethernet90        357,358,359,360                          twohundredGigE0/90     90           200000
Ethernet91        361,362,363,364                          twohundredGigE0/91     91           200000
Ethernet92        365,366,367,368                          twohundredGigE0/92     92           200000
Ethernet93        369,370,371,372                          twohundredGigE0/93     93           200000
Ethernet94        373,374,375,376                          twohundredGigE0/94     94           200000
Ethernet95        377,378,379,380                          twohundredGigE0/95     95           200000
Ethernet96        381,382,383,384                          twohundredGigE0/96     96           200000
Ethernet97        385,386,387,388                          twohundredGigE0/97     97           200000
Ethernet98        389,390,391,392                          twohundredGigE0/98     98           200000
Ethernet99        393,394,395,396                          twohundredGigE0/99     99           200000
Ethernet100       397,398,399,400                          twohundredGigE0/100    100          200000
Ethernet101       401,402,403,404                          twohundredGigE0/101    101          200000
Ethernet102       405,406,407,408                          twohundredGigE0/102    102          200000
Ethernet103       409,410,411,412                          twohundredGigE0/103    103          200000
Ethernet104       413,414,415,416                          twohundredGigE0/104    104          200000
Ethernet105       417,418,419,420                          twohundredGigE0/105    105          200000
Ethernet106       421,422,423,424                          twohundredGigE0/106    106          200000
Ethernet107       425,426,427,428                          twohundredGigE0/107    107          200000
Ethernet108       429,430,431,432                          twohundredGigE0/108    108          200000
Ethernet109       433,434,435,436                          twohundredGigE0/109    109          200000
Ethernet110       437,438,439,440                          twohundredGigE0/110    110          200000
Ethernet111       441,442,443,444                          twohundredGigE0/111    111          200000
Ethernet112       445,446,447,448                          twohundredGigE0/112    112          200000
Ethernet113       449,450,451,452                          twohundredGigE0/113    113          200000
Ethernet114       453,454,455,456                          twohundredGigE0/114    114          200000
Ethernet115       457,458,459,460                          twohundredGigE0/115    115          200000
Ethernet116       461,462,463,464                          twohundredGigE0/116    116          200000
Ethernet117       465,466,467,468                          twohundredGigE0/117    117          200000
Ethernet118       469,470,471,472                          twohundredGigE0/118    118          200000
Ethernet119       473,474,475,476                          twohundredGigE0/119    119          200000
Ethernet120       477,478,479,480                          twohundredGigE0/120    120          200000
Ethernet121       481,482,483,484                          twohundredGigE0/121    121          200000
Ethernet122       485,486,487,488                          twohundredGigE0/122    122          200000
Ethernet123       489,490,491,492                          twohundredGigE0/123    123          200000
Ethernet124       493,494,495,496                          twohundredGigE0/124    124          200000
Ethernet125       497,498,499,500                          twohundredGigE0/125    125          200000
Ethernet126       501,502,503,504                          twohundredGigE0/126    126          200000
Ethernet127       505,506,507,508                          twohundredGigE0/127    127          200000
Ethernet128       509,510,511,512                          twohundredGigE0/128    128          200000