---
device:
    0:
        DEVICE_CONFIG:
            AUTOLOAD_BOARD_SETTINGS: 0
...

---
device:
    0:
        PC_PM_CORE:
            ?
                PC_PM_ID: 1
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x21736405
                RX_LANE_MAP: 0x01573264
                TX_POLARITY_FLIP: 0xf0
                RX_POLARITY_FLIP: 0xb0
            ?
                PC_PM_ID: 2
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x46735021
                RX_LANE_MAP: 0x64103275
                TX_POLARITY_FLIP: 0xcc
                RX_POLARITY_FLIP: 0x13
            ?
                PC_PM_ID: 3
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x46735021
                RX_LANE_MAP: 0x64103275
                TX_POLARITY_FLIP: 0xcc
                RX_POLARITY_FLIP: 0x13
            ?
                PC_PM_ID: 4
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x46735021
                RX_LANE_MAP: 0x64103275
                TX_POLARITY_FLIP: 0xcc
                RX_POLARITY_FLIP: 0x13
            ?
                PC_PM_ID: 5
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x46735021
                RX_LANE_MAP: 0x64103275
                TX_POLARITY_FLIP: 0xce
                RX_POLARITY_FLIP: 0x6c
            ?
                PC_PM_ID: 6
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x21736405
                RX_LANE_MAP: 0x01573264
                TX_POLARITY_FLIP: 0xfc
                RX_POLARITY_FLIP: 0xb0
            ?
                PC_PM_ID: 7
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x37641205
                RX_LANE_MAP: 0x01465723
                TX_POLARITY_FLIP: 0x03
                RX_POLARITY_FLIP: 0x2c
            ?
                PC_PM_ID: 8
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x37641205
                RX_LANE_MAP: 0x01465723
                TX_POLARITY_FLIP: 0x03
                RX_POLARITY_FLIP: 0x2c
            ?
                PC_PM_ID: 9
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x64230517
                RX_LANE_MAP: 0x45026713
                TX_POLARITY_FLIP: 0x3d
                RX_POLARITY_FLIP: 0xce
            ?
                PC_PM_ID: 10
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x20643175
                RX_LANE_MAP: 0x31752064
                TX_POLARITY_FLIP: 0x0f
                RX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 11
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x46025713
                RX_LANE_MAP: 0x57134602
                TX_POLARITY_FLIP: 0x0f
                RX_POLARITY_FLIP: 0x0f
            ?
                PC_PM_ID: 12
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x32467150
                RX_LANE_MAP: 0x20543176
                TX_POLARITY_FLIP: 0xcb
                RX_POLARITY_FLIP: 0x37
            ?
                PC_PM_ID: 13
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x46735021
                RX_LANE_MAP: 0x64103275
                TX_POLARITY_FLIP: 0x0c
                RX_POLARITY_FLIP: 0x43
            ?
                PC_PM_ID: 14
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x46735021
                RX_LANE_MAP: 0x64103275
                TX_POLARITY_FLIP: 0x0c
                RX_POLARITY_FLIP: 0x43
            ?
                PC_PM_ID: 15
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x05647321
                RX_LANE_MAP: 0x64325701
                TX_POLARITY_FLIP: 0xc0
                RX_POLARITY_FLIP: 0xf1
            ?
                PC_PM_ID: 16
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x37641205
                RX_LANE_MAP: 0x01465723
                TX_POLARITY_FLIP: 0x37
                RX_POLARITY_FLIP: 0x63
            ?
                PC_PM_ID: 17
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x37641205
                RX_LANE_MAP: 0x01465723
                TX_POLARITY_FLIP: 0x33
                RX_POLARITY_FLIP: 0x8c
            ?
                PC_PM_ID: 18
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x37641205
                RX_LANE_MAP: 0x01465723
                TX_POLARITY_FLIP: 0x33
                RX_POLARITY_FLIP: 0x8c
            ?
                PC_PM_ID: 19
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x37641205
                RX_LANE_MAP: 0x01465723
                TX_POLARITY_FLIP: 0x33
                RX_POLARITY_FLIP: 0x8c
            ?
                PC_PM_ID: 20
                CORE_INDEX: 0
            :
                TX_LANE_MAP_AUTO: 0
                RX_LANE_MAP_AUTO: 0
                TX_POLARITY_FLIP_AUTO: 0
                RX_POLARITY_FLIP_AUTO: 0
                TX_LANE_MAP: 0x05647321
                RX_LANE_MAP: 0x64325701
                TX_POLARITY_FLIP: 0xf0
                RX_POLARITY_FLIP: 0xf1
...

---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 7
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 9
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 24
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 26
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 28
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 30
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 44
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 46
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 48
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 50
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 52
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 66
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 68
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 70
            :
                PC_PHYS_PORT_ID: 69
            ?
                PORT_ID: 72
            :
                PC_PHYS_PORT_ID: 73
            ?
                PORT_ID: 74
            :
                PC_PHYS_PORT_ID: 77
            ?
                PORT_ID: 88
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 90
            :
                PC_PHYS_PORT_ID: 85
            ?
                PORT_ID: 92
            :
                PC_PHYS_PORT_ID: 89
            ?
                PORT_ID: 94
            :
                PC_PHYS_PORT_ID: 93
            ?
                PORT_ID: 96
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 110
            :
                PC_PHYS_PORT_ID: 101
            ?
                PORT_ID: 112
            :
                PC_PHYS_PORT_ID: 105
            ?
                PORT_ID: 114
            :
                PC_PHYS_PORT_ID: 109
            ?
                PORT_ID: 116
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 118
            :
                PC_PHYS_PORT_ID: 117
            ?
                PORT_ID: 132
            :
                PC_PHYS_PORT_ID: 121
            ?
                PORT_ID: 134
            :
                PC_PHYS_PORT_ID: 125
            ?
                PORT_ID: 136
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 138
            :
                PC_PHYS_PORT_ID: 133
            ?
                PORT_ID: 140
            :
                PC_PHYS_PORT_ID: 137
            ?
                PORT_ID: 154
            :
                PC_PHYS_PORT_ID: 141
            ?
                PORT_ID: 156
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 158
            :
                PC_PHYS_PORT_ID: 149
            ?
                PORT_ID: 160
            :
                PC_PHYS_PORT_ID: 153
            ?
                PORT_ID: 162
            :
                PC_PHYS_PORT_ID: 157
                # management port
            ?
                PORT_ID: 64
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 174
            :
                PC_PHYS_PORT_ID: 162
...

---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [1, 3, 5, 7, 9, 22, 24, 26, 28, 30, 44, 46, 48, 50, 52, 66, 68, 70, 72, 74, 88, 90, 92, 94, 96, 110, 112, 114, 116, 118, 132, 134, 136, 138, 140, 154, 156, 158, 160, 162]
            :
                ENABLE: 1
                SPEED: 400000
                NUM_LANES: 4
                FEC_MODE: PC_FEC_RS544_2XN
                LINK_TRAINING: 1
                MAX_FRAME_SIZE: 9416
            ?
                PORT_ID: [64, 174]
            :
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
                MAX_FRAME_SIZE: 9416
...

---
device:
    0:
        PC_PMD_FIRMWARE:
            ?
                PORT_ID: [1, 3, 5, 7, 9, 22, 24, 26, 28, 30, 44, 46, 48, 50, 52, 66, 68, 70, 72, 74, 88, 90, 92, 94, 96, 110, 112, 114, 116, 118, 132, 134, 136, 138, 140, 154, 156, 158, 160, 162]
            :
                MEDIUM_TYPE_AUTO: 0
                MEDIUM_TYPE: PC_PHY_MEDIUM_COPPER
...

---
device:
    0:
        TM_SCHEDULER_CONFIG:
            NUM_MC_Q: NUM_MC_Q_4
...

---
bcm_device:
    0:
        global:
            bcm_tunnel_term_compatible_mode: 1
            vlan_flooding_l2mc_num_reserved: 2048
            l3_alpm_template: 2
            l3_alpm2_bnk_threshold: 100
            uft_mode: 1
            l3_enable: 1
            l2_hitbit_enable: 0
...

---
bcm_device:
    0:
        port:
            "*":
                encap_mode: IEEE
                dport_map_enable: 1
            160:
                dport_map_port: 1
            162:
                dport_map_port: 2
            116:
                dport_map_port: 3
            118:
                dport_map_port: 4
            44:
                dport_map_port: 5
            46:
                dport_map_port: 6
            1:
                dport_map_port: 7
            3:
                dport_map_port: 8
            5:
                dport_map_port: 9
            7:
                dport_map_port: 10
            9:
                dport_map_port: 11
            22:
                dport_map_port: 12
            24:
                dport_map_port: 13
            26:
                dport_map_port: 14
            28:
                dport_map_port: 15
            30:
                dport_map_port: 16
            48:
                dport_map_port: 17
            50:
                dport_map_port: 18
            52:
                dport_map_port: 19
            66:
                dport_map_port: 20
            68:
                dport_map_port: 21
            70:
                dport_map_port: 22
            72:
                dport_map_port: 23
            74:
                dport_map_port: 24
            88:
                dport_map_port: 25
            90:
                dport_map_port: 26
            92:
                dport_map_port: 27
            94:
                dport_map_port: 28
            96:
                dport_map_port: 29
            110:
                dport_map_port: 30
            112:
                dport_map_port: 31
            114:
                dport_map_port: 32
            132:
                dport_map_port: 33
            134:
                dport_map_port: 34
            136:
                dport_map_port: 35
            138:
                dport_map_port: 36
            140:
                dport_map_port: 37
            154:
                dport_map_port: 38
            156:
                dport_map_port: 39
            158:
                dport_map_port: 40
            64:
                dport_map_port: 41
            174:
                dport_map_port: 42
...

